# Generated by Django 3.2.3 on 2021-05-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checkList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.checklist', verbose_name='Чек лист'),
        ),
    ]
