# Generated by Django 3.2.3 on 2021-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210530_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=150, verbose_name='Опсианеи'),
        ),
    ]
